export enum StatusOperation {
  NONE = 'NONE',
  OK = 'OK',
  SEND_CARDS = 'SEND_CARDS',
  NOT_FOUND_CARDS = 'NOT_FOUND_CARDS',
  FETCH_SAVE_ERROR = 'FETCH_SAVE_ERROR',
  CONFIG_SELECTOR_ERROR = 'CONFIG_SELECTOR_ERROR',
}
